language: python
dist: bionic
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install antlr4
install:
  - pip install -r requirements.txt
script:
  - antlr4 -Dlanguage=Python3 ./src/language/antlr/query.g4 -visitor
  - pytest